// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: pkg/api/proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data type enum
type DataType int32

const (
	DataType_DATA_TYPE_UNSPECIFIED DataType = 0
	DataType_DATA_TYPE_CREDENTIAL  DataType = 1
	DataType_DATA_TYPE_TEXT        DataType = 2
	DataType_DATA_TYPE_BINARY      DataType = 3
	DataType_DATA_TYPE_CARD        DataType = 4
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_CREDENTIAL",
		2: "DATA_TYPE_TEXT",
		3: "DATA_TYPE_BINARY",
		4: "DATA_TYPE_CARD",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_CREDENTIAL":  1,
		"DATA_TYPE_TEXT":        2,
		"DATA_TYPE_BINARY":      3,
		"DATA_TYPE_CARD":        4,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_pkg_api_proto_gophkeeper_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

// Authentication messages
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Data item messages
type DataItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          DataType               `protobuf:"varint,3,opt,name=type,proto3,enum=api.DataType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,5,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	Deleted       bool                   `protobuf:"varint,10,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataItem) Reset() {
	*x = DataItem{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataItem) ProtoMessage() {}

func (x *DataItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataItem.ProtoReflect.Descriptor instead.
func (*DataItem) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *DataItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DataItem) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *DataItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataItem) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *DataItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DataItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *DataItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DataItem) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type          DataType               `protobuf:"varint,2,opt,name=type,proto3,enum=api.DataType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,4,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *AddItemRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddItemRequest) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *AddItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddItemRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *AddItemRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *AddItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AddItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // Alternative to item_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *GetItemRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *DataItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *GetItemResponse) GetItem() *DataItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type          DataType               `protobuf:"varint,2,opt,name=type,proto3,enum=api.DataType" json:"type,omitempty"` // Filter by type (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *ListItemsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ListItemsRequest) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *ListItemsResponse) GetItems() []*DataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"` // For conflict resolution
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateItemRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateItemRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *UpdateItemRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateItemRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NewVersion    int64                  `protobuf:"varint,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateItemResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteItemRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Synchronization messages
type SyncRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Token             string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	LastSyncTimestamp int64                  `protobuf:"varint,2,opt,name=last_sync_timestamp,json=lastSyncTimestamp,proto3" json:"last_sync_timestamp,omitempty"`
	ClientItems       []*DataItem            `protobuf:"bytes,3,rep,name=client_items,json=clientItems,proto3" json:"client_items,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{15}
}

func (x *SyncRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SyncRequest) GetLastSyncTimestamp() int64 {
	if x != nil {
		return x.LastSyncTimestamp
	}
	return 0
}

func (x *SyncRequest) GetClientItems() []*DataItem {
	if x != nil {
		return x.ClientItems
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DataItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	SyncTimestamp int64                  `protobuf:"varint,2,opt,name=sync_timestamp,json=syncTimestamp,proto3" json:"sync_timestamp,omitempty"`
	Conflicts     []*ConflictItem        `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{16}
}

func (x *SyncResponse) GetItems() []*DataItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SyncResponse) GetSyncTimestamp() int64 {
	if x != nil {
		return x.SyncTimestamp
	}
	return 0
}

func (x *SyncResponse) GetConflicts() []*ConflictItem {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type ConflictItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion *DataItem              `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ClientVersion *DataItem              `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictItem) Reset() {
	*x = ConflictItem{}
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictItem) ProtoMessage() {}

func (x *ConflictItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_gophkeeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictItem.ProtoReflect.Descriptor instead.
func (*ConflictItem) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_gophkeeper_proto_rawDescGZIP(), []int{17}
}

func (x *ConflictItem) GetServerVersion() *DataItem {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

func (x *ConflictItem) GetClientVersion() *DataItem {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

var File_pkg_api_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_pkg_api_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/api/proto/gophkeeper.proto\x12\x03api\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"[\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"X\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xf9\x02\n" +
	"\bDataItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\x04type\x18\x03 \x01(\x0e2\r.api.DataTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x0eencrypted_data\x18\x05 \x01(\fR\rencryptedData\x127\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1b.api.DataItem.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion\x12\x18\n" +
	"\adeleted\x18\n" +
	" \x01(\bR\adeleted\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x02\n" +
	"\x0eAddItemRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.api.DataTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0eencrypted_data\x18\x04 \x01(\fR\rencryptedData\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.api.AddItemRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x0fAddItemResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"S\n" +
	"\x0eGetItemRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"4\n" +
	"\x0fGetItemResponse\x12!\n" +
	"\x04item\x18\x01 \x01(\v2\r.api.DataItemR\x04item\"K\n" +
	"\x10ListItemsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\x04type\x18\x02 \x01(\x0e2\r.api.DataTypeR\x04type\"8\n" +
	"\x11ListItemsResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.api.DataItemR\x05items\"\x82\x02\n" +
	"\x11UpdateItemRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.api.UpdateItemRequest.MetadataEntryR\bmetadata\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x12UpdateItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\x03R\n" +
	"newVersion\"B\n" +
	"\x11DeleteItemRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\".\n" +
	"\x12DeleteItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x85\x01\n" +
	"\vSyncRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12.\n" +
	"\x13last_sync_timestamp\x18\x02 \x01(\x03R\x11lastSyncTimestamp\x120\n" +
	"\fclient_items\x18\x03 \x03(\v2\r.api.DataItemR\vclientItems\"\x8b\x01\n" +
	"\fSyncResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.api.DataItemR\x05items\x12%\n" +
	"\x0esync_timestamp\x18\x02 \x01(\x03R\rsyncTimestamp\x12/\n" +
	"\tconflicts\x18\x03 \x03(\v2\x11.api.ConflictItemR\tconflicts\"z\n" +
	"\fConflictItem\x124\n" +
	"\x0eserver_version\x18\x01 \x01(\v2\r.api.DataItemR\rserverVersion\x124\n" +
	"\x0eclient_version\x18\x02 \x01(\v2\r.api.DataItemR\rclientVersion*}\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DATA_TYPE_CREDENTIAL\x10\x01\x12\x12\n" +
	"\x0eDATA_TYPE_TEXT\x10\x02\x12\x14\n" +
	"\x10DATA_TYPE_BINARY\x10\x03\x12\x12\n" +
	"\x0eDATA_TYPE_CARD\x10\x042\xc8\x03\n" +
	"\n" +
	"GophKeeper\x127\n" +
	"\bRegister\x12\x14.api.RegisterRequest\x1a\x15.api.RegisterResponse\x12.\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse\x124\n" +
	"\aAddItem\x12\x13.api.AddItemRequest\x1a\x14.api.AddItemResponse\x124\n" +
	"\aGetItem\x12\x13.api.GetItemRequest\x1a\x14.api.GetItemResponse\x12:\n" +
	"\tListItems\x12\x15.api.ListItemsRequest\x1a\x16.api.ListItemsResponse\x12=\n" +
	"\n" +
	"UpdateItem\x12\x16.api.UpdateItemRequest\x1a\x17.api.UpdateItemResponse\x12=\n" +
	"\n" +
	"DeleteItem\x12\x16.api.DeleteItemRequest\x1a\x17.api.DeleteItemResponse\x12+\n" +
	"\x04Sync\x12\x10.api.SyncRequest\x1a\x11.api.SyncResponseB*Z(github.com/ar11/gophkeeper/pkg/api/protob\x06proto3"

var (
	file_pkg_api_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_pkg_api_proto_gophkeeper_proto_rawDescData []byte
)

func file_pkg_api_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_gophkeeper_proto_rawDesc), len(file_pkg_api_proto_gophkeeper_proto_rawDesc)))
	})
	return file_pkg_api_proto_gophkeeper_proto_rawDescData
}

var file_pkg_api_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_pkg_api_proto_gophkeeper_proto_goTypes = []any{
	(DataType)(0),              // 0: api.DataType
	(*RegisterRequest)(nil),    // 1: api.RegisterRequest
	(*RegisterResponse)(nil),   // 2: api.RegisterResponse
	(*LoginRequest)(nil),       // 3: api.LoginRequest
	(*LoginResponse)(nil),      // 4: api.LoginResponse
	(*DataItem)(nil),           // 5: api.DataItem
	(*AddItemRequest)(nil),     // 6: api.AddItemRequest
	(*AddItemResponse)(nil),    // 7: api.AddItemResponse
	(*GetItemRequest)(nil),     // 8: api.GetItemRequest
	(*GetItemResponse)(nil),    // 9: api.GetItemResponse
	(*ListItemsRequest)(nil),   // 10: api.ListItemsRequest
	(*ListItemsResponse)(nil),  // 11: api.ListItemsResponse
	(*UpdateItemRequest)(nil),  // 12: api.UpdateItemRequest
	(*UpdateItemResponse)(nil), // 13: api.UpdateItemResponse
	(*DeleteItemRequest)(nil),  // 14: api.DeleteItemRequest
	(*DeleteItemResponse)(nil), // 15: api.DeleteItemResponse
	(*SyncRequest)(nil),        // 16: api.SyncRequest
	(*SyncResponse)(nil),       // 17: api.SyncResponse
	(*ConflictItem)(nil),       // 18: api.ConflictItem
	nil,                        // 19: api.DataItem.MetadataEntry
	nil,                        // 20: api.AddItemRequest.MetadataEntry
	nil,                        // 21: api.UpdateItemRequest.MetadataEntry
}
var file_pkg_api_proto_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: api.DataItem.type:type_name -> api.DataType
	19, // 1: api.DataItem.metadata:type_name -> api.DataItem.MetadataEntry
	0,  // 2: api.AddItemRequest.type:type_name -> api.DataType
	20, // 3: api.AddItemRequest.metadata:type_name -> api.AddItemRequest.MetadataEntry
	5,  // 4: api.GetItemResponse.item:type_name -> api.DataItem
	0,  // 5: api.ListItemsRequest.type:type_name -> api.DataType
	5,  // 6: api.ListItemsResponse.items:type_name -> api.DataItem
	21, // 7: api.UpdateItemRequest.metadata:type_name -> api.UpdateItemRequest.MetadataEntry
	5,  // 8: api.SyncRequest.client_items:type_name -> api.DataItem
	5,  // 9: api.SyncResponse.items:type_name -> api.DataItem
	18, // 10: api.SyncResponse.conflicts:type_name -> api.ConflictItem
	5,  // 11: api.ConflictItem.server_version:type_name -> api.DataItem
	5,  // 12: api.ConflictItem.client_version:type_name -> api.DataItem
	1,  // 13: api.GophKeeper.Register:input_type -> api.RegisterRequest
	3,  // 14: api.GophKeeper.Login:input_type -> api.LoginRequest
	6,  // 15: api.GophKeeper.AddItem:input_type -> api.AddItemRequest
	8,  // 16: api.GophKeeper.GetItem:input_type -> api.GetItemRequest
	10, // 17: api.GophKeeper.ListItems:input_type -> api.ListItemsRequest
	12, // 18: api.GophKeeper.UpdateItem:input_type -> api.UpdateItemRequest
	14, // 19: api.GophKeeper.DeleteItem:input_type -> api.DeleteItemRequest
	16, // 20: api.GophKeeper.Sync:input_type -> api.SyncRequest
	2,  // 21: api.GophKeeper.Register:output_type -> api.RegisterResponse
	4,  // 22: api.GophKeeper.Login:output_type -> api.LoginResponse
	7,  // 23: api.GophKeeper.AddItem:output_type -> api.AddItemResponse
	9,  // 24: api.GophKeeper.GetItem:output_type -> api.GetItemResponse
	11, // 25: api.GophKeeper.ListItems:output_type -> api.ListItemsResponse
	13, // 26: api.GophKeeper.UpdateItem:output_type -> api.UpdateItemResponse
	15, // 27: api.GophKeeper.DeleteItem:output_type -> api.DeleteItemResponse
	17, // 28: api.GophKeeper.Sync:output_type -> api.SyncResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_gophkeeper_proto_init() }
func file_pkg_api_proto_gophkeeper_proto_init() {
	if File_pkg_api_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_gophkeeper_proto_rawDesc), len(file_pkg_api_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_pkg_api_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_pkg_api_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_gophkeeper_proto = out.File
	file_pkg_api_proto_gophkeeper_proto_goTypes = nil
	file_pkg_api_proto_gophkeeper_proto_depIdxs = nil
}
